"""pi

Revision ID: 01f92c06a188
Revises: 
Create Date: 2023-12-24 13:59:16.262691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f92c06a188'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pfp_url', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('privilege', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_User_created_at'), 'User', ['created_at'], unique=False)
    op.create_index(op.f('ix_User_first_name'), 'User', ['first_name'], unique=False)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_index(op.f('ix_User_last_name'), 'User', ['last_name'], unique=False)
    op.create_index(op.f('ix_User_mail'), 'User', ['mail'], unique=True)
    op.create_index(op.f('ix_User_pfp_url'), 'User', ['pfp_url'], unique=False)
    op.create_index(op.f('ix_User_privilege'), 'User', ['privilege'], unique=False)
    op.create_table('Card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('time_start', sa.Integer(), nullable=True),
    sa.Column('time_end', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Card_category'), 'Card', ['category'], unique=False)
    op.create_index(op.f('ix_Card_description'), 'Card', ['description'], unique=True)
    op.create_index(op.f('ix_Card_id'), 'Card', ['id'], unique=False)
    op.create_index(op.f('ix_Card_likes'), 'Card', ['likes'], unique=False)
    op.create_index(op.f('ix_Card_name'), 'Card', ['name'], unique=True)
    op.create_index(op.f('ix_Card_tags'), 'Card', ['tags'], unique=False)
    op.create_index(op.f('ix_Card_time_end'), 'Card', ['time_end'], unique=False)
    op.create_index(op.f('ix_Card_time_start'), 'Card', ['time_start'], unique=False)
    op.create_index(op.f('ix_Card_url'), 'Card', ['url'], unique=False)
    op.create_table('Comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['Card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Comment_id'), 'Comment', ['id'], unique=False)
    op.create_table('Participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['Card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Participation_id'), 'Participation', ['id'], unique=False)
    op.create_table('UserCardLike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['Card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserCardLike')
    op.drop_index(op.f('ix_Participation_id'), table_name='Participation')
    op.drop_table('Participation')
    op.drop_index(op.f('ix_Comment_id'), table_name='Comment')
    op.drop_table('Comment')
    op.drop_index(op.f('ix_Card_url'), table_name='Card')
    op.drop_index(op.f('ix_Card_time_start'), table_name='Card')
    op.drop_index(op.f('ix_Card_time_end'), table_name='Card')
    op.drop_index(op.f('ix_Card_tags'), table_name='Card')
    op.drop_index(op.f('ix_Card_name'), table_name='Card')
    op.drop_index(op.f('ix_Card_likes'), table_name='Card')
    op.drop_index(op.f('ix_Card_id'), table_name='Card')
    op.drop_index(op.f('ix_Card_description'), table_name='Card')
    op.drop_index(op.f('ix_Card_category'), table_name='Card')
    op.drop_table('Card')
    op.drop_index(op.f('ix_User_privilege'), table_name='User')
    op.drop_index(op.f('ix_User_pfp_url'), table_name='User')
    op.drop_index(op.f('ix_User_mail'), table_name='User')
    op.drop_index(op.f('ix_User_last_name'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_first_name'), table_name='User')
    op.drop_index(op.f('ix_User_created_at'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
