"""addssa

Revision ID: 56833d294e06
Revises: 6e6c81c2cd28
Create Date: 2023-12-23 23:15:10.181757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56833d294e06'
down_revision: Union[str, None] = '6e6c81c2cd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Card', sa.Column('likes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Card_likes'), 'Card', ['likes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Card_likes'), table_name='Card')
    op.drop_column('Card', 'likes')
    # ### end Alembic commands ###
