"""addsa

Revision ID: 6e6c81c2cd28
Revises: 
Create Date: 2023-12-23 20:54:17.520052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6c81c2cd28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pfp_url', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('privilege', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_User_created_at'), 'User', ['created_at'], unique=False)
    op.create_index(op.f('ix_User_first_name'), 'User', ['first_name'], unique=False)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_index(op.f('ix_User_last_name'), 'User', ['last_name'], unique=False)
    op.create_index(op.f('ix_User_mail'), 'User', ['mail'], unique=True)
    op.create_index(op.f('ix_User_pfp_url'), 'User', ['pfp_url'], unique=False)
    op.create_index(op.f('ix_User_privilege'), 'User', ['privilege'], unique=False)
    op.create_table('Card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Card_description'), 'Card', ['description'], unique=True)
    op.create_index(op.f('ix_Card_id'), 'Card', ['id'], unique=False)
    op.create_index(op.f('ix_Card_name'), 'Card', ['name'], unique=True)
    op.create_index(op.f('ix_Card_time_end'), 'Card', ['time_end'], unique=False)
    op.create_index(op.f('ix_Card_time_start'), 'Card', ['time_start'], unique=False)
    op.create_table('Video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Video_id'), 'Video', ['id'], unique=False)
    op.create_index(op.f('ix_Video_url'), 'Video', ['url'], unique=False)
    op.create_table('Participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['Card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Participation_id'), 'Participation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Participation_id'), table_name='Participation')
    op.drop_table('Participation')
    op.drop_index(op.f('ix_Video_url'), table_name='Video')
    op.drop_index(op.f('ix_Video_id'), table_name='Video')
    op.drop_table('Video')
    op.drop_index(op.f('ix_Card_time_start'), table_name='Card')
    op.drop_index(op.f('ix_Card_time_end'), table_name='Card')
    op.drop_index(op.f('ix_Card_name'), table_name='Card')
    op.drop_index(op.f('ix_Card_id'), table_name='Card')
    op.drop_index(op.f('ix_Card_description'), table_name='Card')
    op.drop_table('Card')
    op.drop_index(op.f('ix_User_privilege'), table_name='User')
    op.drop_index(op.f('ix_User_pfp_url'), table_name='User')
    op.drop_index(op.f('ix_User_mail'), table_name='User')
    op.drop_index(op.f('ix_User_last_name'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_first_name'), table_name='User')
    op.drop_index(op.f('ix_User_created_at'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
